# .streamlit/secrets.toml

openai_api_key = ""
groq_api_key = ""
elasticsearch_host_url = "" 
elasticsearch_api_key = ""

langchain_tracing_v2 = "true"
langchain_api_key = ""
langchain_endpoint = ""
langchain_project = ""
